blogboard/accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from accounts.views import login_view, logout_view, register_page, user_detail, user_follow, user_unfollow

urlpatterns = [
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^register/', register_page, name='register'),
    url(r'^(?P<pk>\d+)/$', user_detail, name='user-detail'),
    url(r'^(?P<pk>\d+)/follow', user_follow, name='user-follow'),
    url(r'^(?P<pk>\d+)/unfollow', user_unfollow, name='user-unfollow'),

    ]

blogboard/blogboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blogs.views import main_page

urlpatterns = [
	url(r'^blog/', include('blogs.urls', namespace='blogs')),
	url(r'^comment/', include('comments.urls', namespace='comments')),
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
	url(r'^$', main_page, name='main'),
	url(r'^django-rq/', include('django_rq.urls')),
]

blogboard/blogs/urls.py
from django.conf.urls import url
from django.contrib import admin
from blogs.views import blog_detail, blog_follow, blog_unfollow, blog_rate, blog_comment, register_blog, blog_search_list, blog_adv_search_list
#from blogs.views import BlogDetailView

urlpatterns = [
    url(r'^add/$', register_blog, name='register-blog'),
    url(r'^(?P<pk>\d+)/$', blog_detail, name='blog-detail'),
    url(r'^(?P<pk>\d+)/follow', blog_follow, name='blog-follow'),
    url(r'^(?P<pk>\d+)/unfollow', blog_unfollow, name='blog-unfollow'),
    url(r'^(?P<pk>\d+)/rate', blog_rate, name='blog-rate'),
    url(r'^(?P<pk>\d+)/comment', blog_comment, name='blog-comment'),
    url(r'^search/', blog_search_list, name='blog-search'),
    url(r'^advsearch/', blog_adv_search_list, name='blog-adv-search')
]

blogboard/comments/urls.py
from django.conf.urls import url
from comments.views import comment_vote, comment_page, comment_post

urlpatterns = [
    url(r'^vote/(?P<pk>\d+)/$', comment_vote, name='comment-vote'),
    url(r'^view/(?P<pk>\d+)/$', comment_page, name='view-all'),
    url(r'^post/(?P<pk>\d+)/$', comment_post, name='comment-post')
]

blogboard/templates/snippets/advsearchform_snipp.html
{% load math_templates %}

<div>
<form id="searchform" action="{% url 'blogs:blog-adv-search' %}" method='get' enctype="'multipart/form-data">{% csrf_token %}
    <!--{{ searchform.as_p }}-->
    <table>
    {% for field in searchform.visible_fields %}
        {% if not forloop.counter|is_even %}
        <tr>
        {% endif %}
        <th>{{field.label_tag}}</th>
        <td>
          {{ field.errors }}
          {{ field }}
        </td>
            {% if forloop.counter|is_even %}
            </tr>
            {% endif %}

    {% endfor %}
    </table>
    <input type="submit" value="dig">
</form>
</div>

blogboard/templates/snippets/comments_snippet.html
{% include 'snippets/new_comment.html' %}

<div id="comments_container">
{% for comm in comments %}:
    {{ comm.user.username }} on {{ comm.timestamp|timesince }}
    <span>{{ comm.content }}</span> {{ comm.ups }} upvotes, {{ comm.downs }} downvotes </br>

        <span><form method="POST" action="{% url 'comments:comment-vote' comm.id %}" enctype="'multipart/form-data">{% csrf_token %}
        {{ voteform.as_p }}
        <input type="submit" value="vote"></form>
        </span>

    </br>

</br>

{% endfor %}
</div>
</div>

blogboard/templates/snippets/countings.html
<script>
    function showStuff(id) {

        var el_style = document.getElementById(id).style.display
        if ( el_style == 'block' ) {
            document.getElementById(id).style.display = 'none';
        } else {
            document.getElementById(id).style.display = 'block';
        }
    }

</script>
          <table>
                <caption>Legend for barplots</caption>
            <tr><th>Number</th><th>Meaning</th></tr>
            <tr><td>1</td><td>not at all</td></tr>
            <tr><td>2</td><td>a bit</td></tr>
            <tr><td>3</td><td>evenly with other topics</td></tr>
            <tr><td>4</td><td>dominates others</td></tr>
            <tr><td>5</td><td>speaks only about it</td></tr>
            </table>



</br>

<div style="width: 100%; float:clear"><a href="#" onclick="showStuff('plots'); return false">show/hide plots</a></div>
<div id="plots" style="display: block;">
    <div class="table">
        <div class="row">
            <div class="column" style="width: 400; height: 300">
                <canvas id="politics"></canvas>
            </div>
            <div class="column" style="width: 400; height: 300">
                <canvas id="soft_science"></canvas>
            </div>
            <div class="column" style="width: 400; height: 300">
                <canvas id="hard_science"></canvas>
            </div>
            <div class="column" style="width: 400; height: 300">
                <canvas id="fashion"></canvas>
            </div>
        </div>
        <div class="row">
            <div class="column" style="width: 400; height: 300">
                <canvas id="travel"></canvas>
            </div>
            <div class="column" style="width: 400; height: 300">
                <canvas id="culture"></canvas>
            </div>
            <div class="column" style="width: 400; height: 300">
                <canvas id="tech"></canvas>
            </div>
            <div class="column" style="width: 400; height: 300">
                <canvas id="sports"></canvas>
            </div>
        </div>
    </div>
</div>
<div style="float:right; width: 400; height: 300">
            <canvas id="rating"></canvas>
        </div>
<script>
    {% for cat, val in countings.items %}

        var {{ cat }} = document.getElementById("{{ cat }}").getContext("2d");
        var barChart = new Chart({{ cat }}, {
            type: 'bar',
            data: {
            labels: [1,2,3,4,5],
            datasets: [
                {
                    label: '{{ cat }}',
                    backgroundColor: 'rgba(255,190,25,1)',
                    borderColor: 'rgba(0,0,0,1)',
                    data: {{ val }}
                }
            ] },
            options: {
                scales: {
                    yAxes: [{
                        display: false,
                        stacked: true,
                        min: 0,
                        max: {{ maximum }},
                    }]
                }
        }

         });

    {% endfor %}
</script>
<script>

    var ratings = document.getElementById("rating").getContext("2d");
    var barChart = new Chart(ratings, {
            type: 'bar',
            data: {
            labels: ['disliked it', 'dull', 'liked it'],
            datasets: [
                {
                    label: 'ratings',
                    backgroundColor: 'rgba(255,190,25,1)',
                    borderColor: 'rgba(0,0,0,1)',
                    data: {{ g_rating }}
                }
            ] },
            options: {
                scales: {
                    yAxes: [{
                        stacked: true,
                        min: 0,

                    }]
                }
        }

         });

</script>

blogboard/templates/snippets/login_logout.html
{% if request.user.is_authenticated %}

<a href="{% url 'accounts:user-detail' request.user.id %}">Logged as {{ request.user.username }}</a>

<form method="POST" action="{% url 'accounts:logout' %}" enctype="'multipart/form-data">{% csrf_token %}
    {{ logout_form.as_p }}
    <input type="submit" value="Logout">
</form>
{% else %}

<form method="POST" action="{% url 'accounts:login' %}" enctype="'multipart/form-data">{% csrf_token %}
    {{ login_form.as_p }}
    <input type="submit" value="Login">
</form>

<a href="{% url 'accounts:register' %}">Sign up</a>

{% endif %}

blogboard/templates/snippets/new_comment.html
<div id="write_comment">
Write comment:
<form method="POST" action="{% url 'comments:comment-post' blog.id %}" enctype="'multipart/form-data">{% csrf_token %}
    {{ comment_form.as_p }}
    <input type="submit" value="write comment">
</form>
</div>

blogboard/templates/snippets/searchform.html
<div>
<form id="searchform" action="{% url 'blogs:blog-search' %}" method='get' enctype="'multipart/form-data">
    <!--{{ searchform.as_p }}-->
    <table>
    {% for field in searchform.visible_fields %}
        <tr>
        <th>{{field.label_tag}}</th>
        <td>
          {{ field.errors }}
          {{ field }}
        </td>
      </tr>
        {% endfor %}
    </table>

    <input type="submit" value="dig">
</form>
</div>