blogboard/accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from accounts.views import login_view, logout_view, register_page, user_detail, user_follow, user_unfollow

urlpatterns = [
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^register/', register_page, name='register'),
    url(r'^(?P<pk>\d+)/$', user_detail, name='user-detail'),
    url(r'^(?P<pk>\d+)/follow', user_follow, name='user-follow'),
    url(r'^(?P<pk>\d+)/unfollow', user_unfollow, name='user-unfollow'),

    ]

blogboard/blogboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blogs.views import main_page

urlpatterns = [
	url(r'^blog/', include('blogs.urls', namespace='blogs')),
	url(r'^comment/', include('comments.urls', namespace='comments')),
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
	url(r'^$', main_page, name='main'),
	url(r'^django-rq/', include('django_rq.urls')),
]

blogboard/blogs/urls.py
from django.conf.urls import url
from django.contrib import admin
from blogs.views import blog_detail, blog_follow, blog_unfollow, blog_rate, blog_comment, register_blog, blog_search_list, blog_adv_search_list
#from blogs.views import BlogDetailView

urlpatterns = [
    url(r'^add/$', register_blog, name='register-blog'),
    url(r'^(?P<pk>\d+)/$', blog_detail, name='blog-detail'),
    url(r'^(?P<pk>\d+)/follow', blog_follow, name='blog-follow'),
    url(r'^(?P<pk>\d+)/unfollow', blog_unfollow, name='blog-unfollow'),
    url(r'^(?P<pk>\d+)/rate', blog_rate, name='blog-rate'),
    url(r'^(?P<pk>\d+)/comment', blog_comment, name='blog-comment'),
    url(r'^search/', blog_search_list, name='blog-search'),
    url(r'^advsearch/', blog_adv_search_list, name='blog-adv-search')
]

blogboard/comments/urls.py
from django.conf.urls import url
from comments.views import comment_vote, comment_page, comment_post

urlpatterns = [
    url(r'^vote/(?P<pk>\d+)/$', comment_vote, name='comment-vote'),
    url(r'^view/(?P<pk>\d+)/$', comment_page, name='view-all'),
    url(r'^post/(?P<pk>\d+)/$', comment_post, name='comment-post')
]

blogboard/comments/models.py
from django.db import models
from django.db.models import Count
import math as m
from blogs.models import User, Blog

# Create your models here.
votes = [(-1, "downvote"), (1, "upvote")]

class Comment(models.Model):
    user = models.ForeignKey(User)
    blog = models.ForeignKey(Blog)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    binom = models.FloatField(default=0.5, null=True, blank=True)
    ups = models.IntegerField(default=0)
    downs = models.IntegerField(default=0)

    parent = models.ForeignKey('self', related_name="children", blank=True, null=True)

    def set_fks(self, user, blog):
        self.user = user
        self.blog = blog


    def class_str(self):
        return 'comment'

    def __str__(self):
        return self.user.username + " on " + self.blog.name

    def set_parent(self, parent):
        self.parent = parent

    def set_binom(self):
        v_set = self.vote_set.all().values('vote').annotate(countvotes=Count('vote'))
        z = {x['vote']:x['countvotes'] for x in v_set}
        if -1 not in z:
            z[-1] = 0
        if 1 not in z:
            z[1] = 0
        s = z[-1] + z[1]
        if s == 0:
            s = 1
        p = z[1]/float(s)
        q = 1.96
        self.binom = sorted([0, p + q*q/(2*s) - q*m.sqrt(p*(1-p)/s + q*q/(4*s*s)), 1])[1] #wilson interval
        self.ups = z[1]
        self.downs = z[-1]
        self.save()

    class Meta:
        ordering = ['binom']


class Vote(models.Model):
    user = models.ForeignKey(User)
    comment = models.ForeignKey(Comment)
    vote = models.IntegerField(choices=votes)

    def set_fks(self, user, comment):
        self.user = user
        self.comment = comment

blogboard/comments/forms.py
from django import forms
from .models import Comment, Vote, votes

class CommentForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.Textarea)
    path = forms.CharField(widget=forms.HiddenInput)

    class Meta:
        model = Comment
        fields = [
            'content',
            'path'
        ]

    def clean(self, *args, **kwargs):
        content = self.cleaned_data.get("content")
        path = self.cleaned_data.get('path')
        return super(CommentForm, self).clean(*args, **kwargs)

    def set_path(self, path):
        self.initial = {"path": path}


class VoteForm(forms.ModelForm):
    vote = forms.ChoiceField(choices=votes)
    path = forms.CharField(widget=forms.HiddenInput)

    class Meta:
        model = Vote
        fields = [
            'vote',
            'path'
        ]

    def clean(self, *args, **kwargs):
        vote = self.cleaned_data.get("vote")
        path = self.cleaned_data.get("path")
        return super(VoteForm, self).clean(*args, **kwargs)

    def set_path(self, path):
        self.initial = {"path": path}

blogboard/comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Comment, Vote
from .forms import CommentForm, VoteForm
from blogs.models import Blog
import os
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from blogboard.common import blog_and_user
templates_location = os.path.join(os.path.dirname(os.path.dirname(__file__)).rstrip("/blogs"), "templates")
# Create your views here.
def comment_reply(request, pk=None):
    pass

def comment_post(request, pk=None):
    current_user, instance = blog_and_user(request, pk=pk)

    comment_form = CommentForm(request.POST or None)

    if comment_form.is_valid():
        new_comment = comment_form.save(commit=False)
        path = comment_form.cleaned_data.get("path")
        new_comment.set_fks(user=current_user, blog=instance)
        new_comment.save()

        return redirect(path)

    return redirect(comment_form.cleaned_data['path'])

def comment_vote(request, pk=None):
    comment = get_object_or_404(Comment, pk=pk)
    voteform = VoteForm(request.POST or None)
    us = request.user

    if Vote.objects.filter(user=us, comment=comment).exists():
        former_vote = Vote.objects.get(user=us, comment=comment)
        former_vote.delete()

    if voteform.is_valid():
        new_vote = voteform.save(commit=False)

        path = voteform.cleaned_data.get("path")
        new_vote.set_fks(us, comment)
        new_vote.save()
        comment.set_binom()
        return redirect(path)

    return redirect(voteform.cleaned_data['path'])

def comment_page(request, pk=None):
    blog = get_object_or_404(Blog, pk=pk)
    qs = blog.comment_set.all().order_by('binom')
    path = request.path
    voteform = VoteForm(request.POST or None)
    comment_form = CommentForm(request.POST or None)
    comment_form.set_path(path)
    voteform.set_path(path)

    paginator = Paginator(qs, 10)
    comment = request.GET.get('comment')
    try:
        comments = paginator.page(comment)
    except PageNotAnInteger:
        comments = paginator.page(1)

    except EmptyPage:
        comments = paginator.comment(paginator.num_pages)

    context_data = {
        "blog":blog,
        "comments":comments,
        "voteform":voteform,
        "comment_form":comment_form
    }
    return render(request, templates_location+"/comments.html", context_data)

blogboard/templates/account_gate.html
<h1>Login</h1>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form.as_p }}
<input type='submit' value='Login'>
</form>

blogboard/templates/base.html
<head>
    <title>Blog recommendation engine</title>
    <link rel="stylesheet" href="/static/css/blog.css" type="text/css">
</head>

<body>

{% block search %}
{% include 'snippets/searchform.html' %}
{% endblock %}

<a href="{% url 'main' %}">Main page</a></br>

    {% block content %}

    {% endblock %}

<p>miejsce na stopke</p>

</body>

blogboard/templates/blog_detail.html
{% extends 'base.html' %}
{% block content %}

<head>
    <title>{{ blog.name }}</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.bundle.js" type="text/javascript"></script>

</head>

<body>
<div id="main_container">
<h1>{{ blog.name }}</h1>
<p>{{ blog.author }}</p>
<p>{{ blog.description }}</p>

</br>

<div class="login-logout">
{% include 'snippets/login_logout.html' %}
</div>

{% if user_rate %}
<p> You've rated as: {{ user_rate.general_ratings }} </p>
{% endif %}

    Similar blogs:</br>
    {% if similar %}
    {% for el in similar %}
        {{ el.name }} </br>
    {% endfor %}
{% endif %}

{% if request.user.is_authenticated %}

{% if logged_user not in followers %}
OBSERWACJI BRAK
<a href = "{% url 'blogs:blog-follow' blog.id %}">Follow</a> </br>
{% else %}
JUZ TO OBSERWUJESZ KMIOCIE
<a href = "{% url 'blogs:blog-unfollow' blog.id %}">Unfollow</a> </br>
{% endif %}


    </br>

Rate blog:
<form id="rate_form" method="POST" action="{% url 'blogs:blog-rate' blog.id %}" enctype="'multipart/form-data">{% csrf_token %}
    {{ rate_form.as_p }}
    <input id="rate_input" type="submit" value="rate">
</form>

{% endif %}

{% include 'snippets/countings.html' %}


{% if user_rate %}
<p> You've rated as: {{ user_rate.general_ratings }} </p>
{% endif %}




</br>
Sledzacy bloga:
{% for us in followers %}

<p>Uzytkownik: {{ us.user }} </p>

{% endfor %}

</br>
</br>


</br>

{% if comments %}:
Comments - <a href="{% url 'comments:view-all' blog.id %}">view all</a>:

{% include 'snippets/comments_snippet.html' %}

{% else %}
{% include 'snippets/new_comment.html' %}
No comments to display
{% endif %}

</body>

{% endblock %}

blogboard/templates/comments.html
{% extends 'base.html' %}

{% block content %}
<div id="main_container">
<a href="{% url 'blogs:blog-detail' blog.id %} "><h1>{{ blog.name }}</h1></a>
<p>{{ blog.author }}</p>
<p>{{ blog.description }}</p>


{% include 'snippets/comments_snippet.html' %}

<div class="pagination">
    {% if comments.has_previous %}
        <a href="?comment={{ comments.previous_comment_number }}">Previous page</a>
    {% endif %}

    </br>
    Page {{ comments.number }} from {{ comments.paginator.num_pages }}
    </br>

    {% if comments.has_next %}
        <a href="?comment={{ comments.next_comment_number }}">Next page</a>
    {% endif %}
</div>
</div>
{% endblock %}

blogboard/templates/main.html
{% extends 'base.html' %}

{% block content %}

{% include 'snippets/login_logout.html' %}

<h1>Main page</h1>

{% if logged %}
Followed users
{% endif %}
{% if followingusers %}
    {% for us in followingusers %}
        {{ us.username }} </br>
    {% endfor %}
{% endif %}

</br>
</br>

{% if logged %}
Followed blogs </br>
{% endif %}
{% for blog in blogs_iq %}
<a href="{% url 'blogs:blog-detail' blog.id %}">{{ blog.name }} </a></br>
{% endfor %}
</br>

{% if logged %}
    Followed users liked: </br>
    {% for el in foll_likes %}
        {{ el.name }} </br>
    {% endfor %}
    </br>

    Your feed: </br>
    {% for el in show_list %}
        {% if el.class_str == 'rating' %}
            {{ el.user.username }} rated {{ el.blog.name }} at {{ el.general_ratings }} {{ el.timestamp|timesince }} ago </br>
        {% else %}
            {{ el.user.username }} commented {{ el.blog.name }} with {{ el.content }} {{ el.timestamp|timesince }} ago </br>
        {% endif %}
    {% endfor %}
{% endif %}

<h2>Most popular blogs</h2>
{% for el in popular %}
    <a href="{% url 'blogs:blog-detail' el.id %}">{{ el.name }} </a></br>
{% endfor %}


<h3>Most popular in seperate categories</h3>
{% for cat, elements in cat_popularity.items %}
    <h4> {{ cat }} </h4> </br>
    {% for el in elements %}
        <a href="{% url 'blogs:blog-detail' el.id %}">{{ el.name }} </a></br>
    {% endfor %}
</br>
{% endfor %}

{% endblock %}

blogboard/templates/register.html
<h1>register</h1>

<form method="POST" action="" enctype="'multipart/form-data">{% csrf_token %}
    {{ user_form.as_p }}
    {{ user_likes.as_p }}
    <input type="submit" value="register and confirm preferences">
</form>

blogboard/templates/register_blog.html
{% extends 'base.html' %}

{% block content %}

<h1>enter blog to the database</h1>

<form method="POST" action="" enctype="'multipart/form-data">{% csrf_token %}
    {{ newblog.as_p }}
    <input type="submit" value="enter blog to database">
</form>

{% endblock %}

blogboard/templates/searchlist.html
{% extends 'base.html' %}

{% load math_templates %}

{% block search %}

{% include 'snippets/advsearchform_snipp.html' %}


{% endblock %}

{% block content %}


{% if result_list %}

    {% for el in result_list %}
        {{ el.name }}, {{ el.description }} </br>
    {% endfor %}

{% else %}
No seach results ( yet? )

{% endif %}

{% endblock %}

blogboard/templates/userfollowings_detail.html
{% extends 'base.html' %}
{% block content %}

{% include 'snippets/login_logout.html' %}

<head>
    <title>{{ user_iq.username }}</title>
</head>

<p>Znajdujesz sie na stronie poswieconej</p>
{{ user_iq.username }}

<p>Milej zabawy</p>
Blogs he follows
{% for blog in followingblogs %}
<a href="{% url 'blogs:blog-detail' blog.id %}">{{ blog.name }} </a></br>
{% endfor %}

</br> </br>

{% if logged and current_user.user != user_iq %}

{% if current_user not in followers %}
        OBSERWACJI BRAK
        <a href = "{% url 'accounts:user-follow' user_iq.id %}">Follow</a> </br>
{% else %}
        JUZ TO OBSERWUJESZ KMIOCIE
        <a href = "{% url 'accounts:user-unfollow' user_iq.id %}">Unfollow</a> </br>
{% endif %}
{% endif %}



</br>
People he follows
</br>
{% for us in followingusers %}
{{ us.username }}</br>
{% endfor %}

</br>
Followers
</br>

{% for us in followers %}
{{ us.user.username }}</br>
{% endfor %}

</br>

{% for el in show_list %}
{% if el.class_str == 'rating' %}
    {{ user_iq.username }} rated {{ el.blog.name }} at {{ el.general_ratings }} {{ el.timestamp|timesince }} ago </br>
{% else %}
    {{ user_iq.username }} commented {{ el.blog.name }} with {{ el.content }} {{ el.timestamp|timesince }} ago </br>
{% endif %}

{% endfor %}

{% endblock %}